### ISSUE TITLE
Example of how to run the script?

### ISSUE THREAD

**Issue by singpolyma** [mcepl/github-issues-export#3]
I'm getting `urllib2.HTTPError: HTTP Error 404: Not Found` -- maybe bitrot?

**Comment by mcepl** [comment]
```python
matej@mitmanek: github-issues-export (03_unbitrot *)$ ./github_issues_export.py 
Traceback (most recent call last):
  File "./github_issues_export.py", line 341, in <module>
    main(config)
  File "./github_issues_export.py", line 326, in main
    conf['repo'], state=state):
  File "./github_issues_export.py", line 292, in get_issues
    handler = urllib2.urlopen(req)
  File "/usr/lib64/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib64/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 404: Not Found
```

**Comment by mcepl** [comment]
This is example of running the script:
```
$ python github_issues_export.py  mcepl/github-issues-export >/tmp/bugs.xml
INFO:main:It is necessary to fix all email addresses
to correspond to bugzilla users.

Also, for importxml.pl to succeed you have to have switched on
 * move-enabled
 * moved-default-product
 * moved-default-component

$
```
and notice that you have to use `-u` and `-p` parameters to set credentials or you have to have `~/.githubrc` file of roughly this content:
```ini
[github]
user=jdoe
password=veryverysecret
```
Notice also that we have no `setup.py` so please install this script (and there is `urllib2_prior_auth` module from PyPI as new dependency).

Please, test the code from branch `03_unbitrot` and let me know whether your issue has been fixed.

**Comment by mcepl** [comment]
BTW, looking at your repo https://github.com/singpolyma/git-ticket I think you might be interested in https://github.com/mcepl/git-tkt, https://github.com/mcepl/git-tkt, https://github.com/mcepl/git-issues, and https://github.com/mcepl/gitshelve. Pull requests are very welcome (of course ;))!

**Comment by singpolyma** [comment]
@mcepl invoking as in your example seems to work even on `master` and with no auth switches or file of any kind.
